version: "3"
services:
  spigot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        version: latest
    env_file:
    - spigot-variables.env
    volumes:
      - ./mcdata/:/data
    ports:
      - ${PORT}:25565
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - spigot-network

networks:
  spigot-network:
